/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admissionsystem;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class collegeHome extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    ArrayList<student> stds;
    student s;
    college c;
    int count = 0;
    /**
     * 
     * Creates new form adminHome
     */
    public collegeHome() {
        initComponents();
    }

    collegeHome(college c) throws FileNotFoundException {
        initComponents();
        stds = new ArrayList();
        s = new student();
        jLabel2.setText(c.getName());
        
                    this.c = new college();
                    this.c.setName(c.getName());
                    this.c.setCity(c.getCity());
                    this.c.setAddress(c.getAddress());                   
                    this.c.setEmail(c.getEmail()); 
                    this.c.setPhone(c.getPhone());
                    this.c.setYear(c.getYear());
                    this.c.setStrength(c.getStrength());
                    this.c.setMale(c.getMale());
                    this.c.setFemale(c.getFemale());
                    this.c.setFees(c.getFemale());
                    this.c.setSubs(c.getSubs());
                    for(int i = 0; i < c.subjects.size(); i++) {
                        this.c.subjects.add(c.subjects.get(i));
                        this.c.teachers.add(c.teachers.get(i));
                    }
                    
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("College Home");

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("College Home");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View All Student Applications");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("College Profile");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(51, 51, 51)
                .addComponent(jButton4)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new viewCollege(c).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://Students.accdb");
            pst = con.prepareStatement("select * from students");
            rs = pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            while(rs.next())
            {
               s = new student();
                
              String str = rs.getString("Colleges");
              
                    
                    
                    if (!java.util.Objects.equals(str,null)) {
                        if(rs.getString("Colleges").contains(",")) {
                            String[] colleges = rs.getString("Colleges").split(",");
                            String[] appStatus = rs.getString("ApplicationStatus").split(",");
                                for(int i = 0; i < colleges.length; i++) {
                                    if(i == 0) {
                                        this.s.colleges.add(colleges[i].substring(1));
                                        this.s.applicationStatus.add(appStatus[i].substring(1));
                                    }
                                    else if(i == colleges.length - 1) {
                                        this.s.colleges.add(colleges[i].trim().substring(0,colleges[i].trim().length() - 1));
                                        this.s.applicationStatus.add(appStatus[i].trim().substring(0,appStatus[i].trim().length() - 1));
                                    }
                                    else {
                                        this.s.colleges.add(colleges[i].trim());
                                        this.s.applicationStatus.add(appStatus[i].trim());
                                    }
                                }
                        }
                        else {
                            this.s.colleges.add(rs.getString("Colleges").substring(1,rs.getString("Colleges").length() - 1));
                            this.s.applicationStatus.add(rs.getString("ApplicationStatus").substring(1,rs.getString("ApplicationStatus").length() - 1));
                        }
                        for(int a = 0; a < s.colleges.size(); a++) {
                            if (s.colleges.get(a).equals(c.getName())) {
                                    count++;
                                    this.s.setName(rs.getString("Fullname"));
                                    this.s.setCnic(rs.getString("CNIC"));
                                    this.s.setUsername(rs.getString("Username"));
                                    this.s.setDOB(rs.getString("DOB"));
                                    this.s.setGender(rs.getString("Gender"));
                                    this.s.setEmail(rs.getString("email"));
                                    this.s.setPhone(rs.getString("Phone"));
                                    this.s.setAddress(rs.getString("Address"));
                                    this.s.setSchool(rs.getString("School"));
                                    this.s.setSubs(Integer.parseInt(rs.getString("NumberOfSubjects")));
                                    this.s.setProfileStatus(Boolean.parseBoolean(rs.getString("ProfileStatus")));
                                    String[] subs = rs.getString("Subjects").split(",");
                                    String[] grades = rs.getString("Grades").split(",");
                                    
                                    for(int i = 0; i < subs.length; i++) {
                                        if(i == 0) {
                                            this.s.subjects.add(subs[i].substring(1));
                                            this.s.grades.add(grades[i].substring(1));
                                        }
                                        else if(i == subs.length - 1) {
                                            this.s.subjects.add(subs[i].trim().substring(0,subs[i].trim().length() - 1));
                                            this.s.grades.add(grades[i].trim().substring(0,grades[i].trim().length() - 1));
                                        }
                                        else {
                                            this.s.subjects.add(subs[i].trim());
                                            this.s.grades.add(grades[i].trim());
                                        }
                                    }
                                    stds.add(s);
                        break;        
                        }
                        
                        
                        
                    }
                    
                    
                    }

        }
            if(count > 0) {
                new studProfs(c,stds).setVisible(true);
                this.setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(this, "No Students have applied yet");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(collegeHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(collegeHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(collegeHome.class.getName()).log(Level.SEVERE, null, ex);
        }
                        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(collegeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(collegeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(collegeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(collegeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new collegeHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
