/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admissionsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class editCollege extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    college c;
    
    public editCollege() {
        initComponents();
    }

    editCollege(college c) {
        initComponents();
        name.setEditable(false);
        //subsTF.setEditable(true);
        //teachersTF.setEditable(true);
        name.setText(c.getName());
        address.setText(c.getAddress());
        contact.setText(c.getPhone());        
        city.setText(c.getCity());        
        email.setText(c.getEmail());
        year.setText(Integer.toString(c.getYear()));
        strength.setText(Integer.toString(c.getStrength()));
        n.setValue(c.getSubs());
        n.setEnabled(true);
       
        male.setText(Double.toString(c.getMale()));
        female.setText(Double.toString(c.getFemale()));
        fees.setText(Double.toString(c.getFees()));
        for(int i = 0; i < c.subjects.size(); i++) {
            subsTF.addItem(c.subjects.get(i));
            teachersTF.addItem(c.teachers.get(i));
        }
        subsTF.setEditable(false);
        teachersTF.setEditable(false);
        
                    this.c = new college();
                    this.c.setName(c.getName());
                    this.c.setCity(c.getCity());
                    this.c.setAddress(c.getAddress());                   
                    this.c.setEmail(c.getEmail()); 
                    this.c.setPhone(c.getPhone());
                    this.c.setYear(c.getYear());
                    this.c.setStrength(c.getStrength());
                    this.c.setMale(c.getMale());
                    this.c.setFemale(c.getFemale());
                    this.c.setFees(c.getFemale());
                    this.c.setSubs(c.getSubs());
                    for(int i = 0; i < c.subjects.size(); i++) {
                        this.c.subjects.add(c.subjects.get(i));
                        this.c.teachers.add(c.teachers.get(i));
                    }
                    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        n = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        strength = new javax.swing.JTextField();
        male = new javax.swing.JTextField();
        female = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        subsTF = new javax.swing.JComboBox<>();
        teachersTF = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("College Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setText("College Name:");

        jLabel3.setText("College City:");

        jLabel4.setText("College Address:");

        jLabel5.setText("College email:");

        jLabel6.setText("College Contact Number:");

        jLabel7.setText(" Year Founded:");

        jLabel8.setText("College Strength:");

        jLabel9.setText("Male Ratio (in %) :");

        jLabel10.setText("Female Ratio (in %) :");

        jLabel11.setText("Monthly Fees:");

        jLabel12.setText(" Number of Subjects:");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        strength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthActionPerformed(evt);
            }
        });

        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Change the fields to Edit");

        jLabel14.setText("Subjects:");

        jLabel15.setText("Teachers:");

        subsTF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subsTFItemStateChanged(evt);
            }
        });
        subsTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subsTFMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subsTFMouseExited(evt);
            }
        });
        subsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsTFActionPerformed(evt);
            }
        });
        subsTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subsTFKeyPressed(evt);
            }
        });

        teachersTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teachersTFKeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setText("Edit Subjects Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(name)
                            .addComponent(city)
                            .addComponent(address)
                            .addComponent(email)
                            .addComponent(contact)
                            .addComponent(year)
                            .addComponent(strength)
                            .addComponent(male)
                            .addComponent(female)
                            .addComponent(fees)
                            .addComponent(subsTF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teachersTF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel13)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel13)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(strength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(subsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachersTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void strengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strengthActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new collegeProfiles().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(editCollege.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(editCollege.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(name.getText().isEmpty() || city.getText().isEmpty() || address.getText().isEmpty() || email.getText().isEmpty() || contact.getText().isEmpty() || year.getText().isEmpty() || strength.getText().isEmpty() || male.getText().isEmpty() || female.getText().isEmpty() || fees.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "All fields should be filled.");
        }
        else if(Integer.parseInt(n.getValue().toString()) < 2) {
            JOptionPane.showMessageDialog(this, "There should be minimum 2 Subjects.");
        }
        else if(Integer.parseInt(n.getValue().toString()) != c.getSubs()) {
            JOptionPane.showMessageDialog(this, "Please Edit Subjects Info as number of subjects are changed.");
        }
       
        else {
            college c = new college();
            c.setName(name.getText());
            c.setCity(city.getText());
            c.setAddress(address.getText());
            c.setEmail(email.getText());
            c.setPhone(contact.getText());
            c.setYear(Integer.parseInt(year.getText()));
            c.setStrength(Integer.parseInt(strength.getText()));
            c.setFees(Double.parseDouble(fees.getText()));
            c.setMale(Double.parseDouble(male.getText()));
            c.setFemale(Double.parseDouble(female.getText()));
            c.setSubs(Integer.parseInt(n.getValue().toString()));
            for(int i = 0; i < c.getSubs(); i++) {
                c.subjects.add(subsTF.getItemAt(i));
                c.teachers.add(teachersTF.getItemAt(i));
            }
            
            
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://Colleges.accdb");
                pst = con.prepareStatement("update colleges set City = ?, Address = ?, email = ?, Phone = ?, YearFounded = ?, Strength = ?, MaleRatio = ?, FemaleRatio = ?, Fees = ?, NumberOfSubjects = ?, Subjects = ?, Teachers = ? where CollegeName = ?");
                pst.setString(13, c.getName());
                pst.setString(1, c.getCity());
                pst.setString(2, c.getAddress());
                pst.setString(3, c.getEmail());
                pst.setString(4, c.getPhone());
                pst.setString(5, Integer.toString(c.getYear()));
                pst.setString(6, Integer.toString(c.getStrength()));
                pst.setString(7, Double.toString(c.getMale()));
                pst.setString(8, Double.toString(c.getFemale()));
                pst.setString(9, Double.toString(c.getFees()));
                pst.setString(10, Integer.toString(c.getSubs()));
    
                pst.setString(11, c.subjects.toString());
                pst.setString(12, c.teachers.toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Details Updated");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(editCollege.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(editCollege.class.getName()).log(Level.SEVERE, null, ex);
            }
                
           
            
            try {
                new collegeProfiles().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(editCollege.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(editCollege.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void subsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subsTFActionPerformed

    private void subsTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subsTFMouseClicked
        teachersTF.setSelectedIndex(subsTF.getSelectedIndex());
    }//GEN-LAST:event_subsTFMouseClicked

    private void subsTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subsTFMouseExited
       teachersTF.setSelectedIndex(subsTF.getSelectedIndex());
    }//GEN-LAST:event_subsTFMouseExited

    private void subsTFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subsTFItemStateChanged
        
    }//GEN-LAST:event_subsTFItemStateChanged

    private void subsTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subsTFKeyPressed
        teachersTF.setSelectedIndex(subsTF.getSelectedIndex());
    }//GEN-LAST:event_subsTFKeyPressed

    private void teachersTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teachersTFKeyPressed
        subsTF.setSelectedIndex(teachersTF.getSelectedIndex());
    }//GEN-LAST:event_teachersTFKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(Integer.parseInt(n.getValue().toString()) < 2) {
            JOptionPane.showMessageDialog(this, "Minimum 2 subjects required");
        }
        else{
        c.setSubs(Integer.parseInt(n.getValue().toString()));
       
                    this.c.setCity(city.getText());
                    this.c.setAddress(address.getText());                   
                    this.c.setEmail(email.getText()); 
                    this.c.setPhone(contact.getText());
                    this.c.setYear(Integer.parseInt(year.getText()));
                    this.c.setStrength(Integer.parseInt(strength.getText()));
                    this.c.setMale(Double.parseDouble(male.getText()));
                    this.c.setFemale(Double.parseDouble(female.getText()));
                    this.c.setFees(Double.parseDouble(fees.getText()));
                    
        new subsInfo(c).setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editCollege.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editCollege().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fees;
    private javax.swing.JTextField female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField male;
    private javax.swing.JSpinner n;
    private javax.swing.JTextField name;
    private javax.swing.JTextField strength;
    private javax.swing.JComboBox<String> subsTF;
    private javax.swing.JComboBox<String> teachersTF;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
